<?php

namespace Acme\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class StartController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Acme\UserBundle\Controller\StartController();
        return $instance;
    }
}
