security:
    encoders:
            Symfony\Component\Security\Core\User\User: plaintext
            FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
            logout:
                path:   /logout
                target: /
            anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/task/edit, roles: ROLE_USER }
        - { path: ^/task/new, roles: ROLE_ADMIN }
        - { path: ^/task/show, roles: ROLE_USER }
        - { path: ^/task, roles: ROLE_ADMIN }
        - { path: ^/solving, roles: ROLE_USER }